[package]
name = "sqlite_rust"
version = "0.1.0"
authors = ["https://www.steadylearner.com/blog/search/Rust"]
edition = "2018"

[dependencies]
chrono = "0.4.11"

[dependencies.rusqlite]
version = "0.21.0"
features = ["chrono"]

