language: rust

env:
    global:
        - secure: T6BZeL6QVLjypktu7nutxMnWxKF0F4AHf1XxIzvCxqI6wHi3JvYfBywOdzfm6lbTd7bNWQjEm2sCG6/2dJ9N7qQ/kQ2w7PjVyLnf4OpAv6WdODvJRjCzH1IDNG+xMW8rGD8c+864w6875c13H4joQHy2i90PQe8yj4gV7dPq6Vg=

script:
    - cargo build
    - cargo test
    - cargo doc --no-deps

after_script:
    - mv target/doc .
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
